Home work lesson7
AlexeySapunov/homeWorkCourse3 pull request #5
Opened 2021-09-22 09:37 UTC by AlexeySapunov

2021-09-22 09:51 UTC, AlexeySapunov reviewed
homeWorkLesson7

2021-09-23 08:40 UTC, efserg requested changes

2021-09-23 08:40 UTC, efserg commented on src/main/java/ru/geekbrains/lesson7/AppTest.java
> +            for (int i = 1; i < 11; i++) {
А что это такое?
Зачем тут этот цикл?

2021-09-23 08:40 UTC, efserg commented on src/main/java/ru/geekbrains/lesson7/AppTest.java
> +                    if (method.getAnnotation(Test.class) != null) {
Тогда уж используйте метод `isAnnotationPresent`

2021-09-23 08:40 UTC, efserg commented on src/main/java/ru/geekbrains/lesson7/AppTest.java
> +            int count1 = 0;
Лучше boolean переменную использовать

2021-09-28 05:27 UTC, merged